# Generated by Django 4.2.7 on 2023-11-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pop_post',
            field=models.BooleanField(default=False),
        ),
    ]
